.Dd $Mdocdate: April 16 2016 $
.Dt FSDG 7
.Os
.Sh NAME
.Nm fsdg
.Nd free software distribution guidelines

.Sh DESCRIPTION
The Free Software Distribution Guidelines (GNU FSDG) are
a set of guidelines put in place by the Free Software Foundation
to define what is required for an operating system to respect the
user's freedom and be considered a fully free operating system.
The LibertyBSD project strives to be fully Free Software and follow these
guidelines.

.Sh GUIDELINES
Summarized, fully free distributions must be:
.Bl -enum
.It
Self-hosting
.It
Fully Free Software
.It
Containing only free functional data and documentation
.It
Deblobbed of non-free firmware 
.It
Unhindered in excerising the four freedoms by trademark law
.It
Without DRM, back-doors, and spyware
.It
Committed to correcting mistakes
.It
Actively maintained
.It
Without a misleading name
.El

.Sh SEE ALSO
.Xr free-software 7

.Sh HISTORY
The fsdg(7) page appeared in LibertyBSD 5.9.
